### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by drvink**

### CODE REVIEW

**Comment by drvink** [comment]
Flycheck itself will need an update in order for tests to pass on Emacs 24.3: `flycheck-ert` uses `define-error`, but Emacs 24.3 didn't have that. I'll make a PR for that on the Flycheck repo.

**Comment by drvink** [comment]
The tests are passing on everything but 24.3 (which was probably just because MELPA doesn't have the updated Flycheck still) and the snapshot version (which looks like some other problem related to the build environment) now.

**Comment by drvink** [comment]
The 24.3 tests are still failing due to `define-error`--it looks like `json` *also* uses it. Flycheck itself doesn't use `define-error`, so I guess I'll just add the defun to the test file here--better than cluttering flycheck's code.

**Comment by bbatsov** [comment]
I guess it's a bit too late, but better late then never. Travis no longer exists at this point and we'll need to replace it with something else (e.g. GHA).

**Pull request merged**
